FROM eclipse-temurin:21.0.3_9-jdk-alpine

# needed for healthcheck
RUN apk add --no-cache curl

COPY target/*.jar app.jar

EXPOSE 8080
VOLUME /opt/uploads

HEALTHCHECK --start-interval=2s --interval=1m --timeout=5s --retries=5 --start-period=90s \
    CMD curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1

ENTRYPOINT ["java", "-jar", "/app.jar"]
