name: Generate API Docs

on:
  workflow_call:
    inputs:
      definition-path:
        required: false
        type: string
        default: src/main/resources/api/**/api.yaml
      name-expression:
        required: false
        type: string
        default: $(basename ${path%/api.yaml})
    secrets:
      API_DOCS_PAT:
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false # spammy

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install redocly CLI
        run: npm install -g @redocly/cli

      - name: Generate documentation
        run: |
          set -x
          echo 'npx @redocly/cli build-docs $path -o out/${{ inputs.name-expression }}.html' > gen.sh
          cat gen.sh
          chmod +x gen.sh
          mkdir -p out
          for path in ${{ inputs.definition-path }}; do
            ./gen.sh
          done

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          path: out
          name: api-docs
