name: Bun Docker Build/Deploy for Next.js

on:
  workflow_call:
    inputs:
      build-root:
        required: false
        type: string
        default: .
      port:
        required: false
        type: number
        default: 3000
      image-name:
        required: false
        type: string
        default: ${{ github.repository }}
      deploy:
        required: false
        type: boolean
        default: true
      service-name:
        required: false
        type: string
        default: ${{ github.repository }}
    secrets:
      TS_OAUTH_CLIENT_ID:
        required: false # only if deploying
      TS_OAUTH_SECRET:
        required: false # only if deploying
      DEPLOY_SSH_USERNAME:
        required: false # only if deploying
      DEPLOY_SSH_HOST:
        required: false # only if deploying

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          show-progress: false # spammy
          path: app

      - name: Checkout template repo
        uses: actions/checkout@v5
        with:
          repository: foxy-development/configs
          fetch-depth: 1
          show-progress: false # spammy
          path: configs

      - name: Generate template
        run: |
          awk '{
            gsub(/\$\{PORT\}/,"${{ inputs.port }}");
            gsub(/\$\{ROOT\}/,"${{ inputs.build-root }}");
            print
          }' configs/docker/Dockerfile.bun-template-next > configs/docker/Dockerfile.bun
          cat configs/docker/Dockerfile.bun

      - name: Print Docker version
        run: docker version

      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ inputs.image-name }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./configs/docker/Dockerfile.bun
          push: ${{ github.ref_name == github.event.repository.default_branch && inputs.deploy }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build]
    if: ${{ github.ref_name == github.event.repository.default_branch && inputs.deploy }}
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      service-name: ${{ inputs.service-name }}
